# Generated by Django 3.1.1 on 2020-09-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('const', '0003_crel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2024, null=True)),
                ('skills', models.JSONField(null=True)),
                ('work_experience', models.PositiveSmallIntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True)),
                ('sts', models.IntegerField(choices=[(-1, 'تایید نشده'), (1, 'تایید'), (2, 'آرشیو شده')], default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'department',
                    models.ForeignKey(on_delete=models.CASCADE, related_name='department', to='const.const')),
                ('education',
                 models.ForeignKey(null=True, on_delete=models.CASCADE, related_name='education', to='const.const')),
                ('job_title', models.ForeignKey(on_delete=models.CASCADE, related_name='job_title', to='const.const')),
                ('org_level',
                 models.ForeignKey(null=True, on_delete=models.CASCADE, related_name='org_level', to='const.const')),
                ('reason',
                 models.ForeignKey(null=True, on_delete=models.CASCADE, related_name='reason', to='const.const')),
                ('workplace',
                 models.ForeignKey(null=True, on_delete=models.CASCADE, related_name='workplace', to='const.const')),
            ],
        ),
    ]
